Update update.yml

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -18,7 +18,8 @@ jobs:
           python-version: '3.x'
 
       - name: Install dependencies
-        run: pip install requests
+        run: |
+          pip install cloudscraper
 
       - name: Run fetch script
         run: python fetch_link.py
@@ -27,13 +28,11 @@ jobs:
         run: |
           git config --global user.name "GitHub Action"
           git config --global user.email "action@github.com"
-          # التحقق من وجود الملف قبل عمل add
           if [ -f live_link.txt ]; then
             git add live_link.txt
-            # لن يقوم بعمل commit إلا إذا كان هناك تغيير حقيقي في المحتوى
-            git commit -m "Update Dubai One Link" || echo "No changes to commit"
+            git commit -m "Update Dubai One Link" || echo "No changes"
             git push
           else
-            echo "File live_link.txt not found, skipping..."
-            exit 1
+            echo "File still not found"
+            exit 0 # غيرناها لـ 0 عشان نشوف النتيجة بدون علامة خطأ حمراء
           fi
